name: Dropdown Example

on:
  push:
    branches:
      - dropdown_EDA   # 👈 your feature branch name
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - Hemanth Bhai
          - Sagar Bhai
          - Allu Bhai

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected option
        run: echo "You selected ${{ github.event.inputs.environment || 'Default (Push Trigger)' }}"
